config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  root 'home#index'

  get 'member/:id', to: 'members#show', as: 'member'

  get 'edit_description', to: 'members#edit_description', as: 'edit_member_description'

  patch 'update_description', to: 'members#update_description', as: 'update_member_description'

  get 'edit_details', to: "members#edit_details", as: 'edit_member_details'

  patch 'update_details', to: 'members#update_details', as: 'update_member_details'

  get 'member-connections/:id', to: 'members#connections', as: 'member_connections'

  resources :work_experiences

  resources :connections
end

app/models/work_experience.rb
class WorkExperience < ApplicationRecord
  EMPLOYMENT_TYPE = %w[Full-time Part-time Self-employed Freelance Trainee Internship].freeze

  LOCATION_TYPE = %w[On-site Hybrid Remote].freeze

  belongs_to :user # as singular

  validates :company, :start_date, :job_title, :location, presence: true

  validates :employment_type, presence: true, inclusion: { in: EMPLOYMENT_TYPE, message: 'not a valid employment type' }

  validates :location_type, presence: true, inclusion: { in: LOCATION_TYPE, message: 'not a valid location type' }

  validate :work_experience_last_date, :presence_of_end_date

  validate :end_date_greater_than_start_date, if: :currently_not_working_here?

  def work_experience_last_date
    return unless end_date.present? && currently_working_here

    errors.add(:end_date, 'must be blank if you are currently working in this company')
  end

  def presence_of_end_date
    return unless end_date.blank? && !currently_working_here

    errors.add(:end_date, 'must be present if you are not currently working in this company')
  end

  def currently_not_working_here?
    !currently_working_here
  end

  def end_date_greater_than_start_date
    return if end_date.nil?

    return unless end_date < start_date

    errors.add(:end_date, 'must be greater than start_date')
  end

  def company_with_employment_type
    %[#{company} (#{employment_type})].strip
  end

  def job_location
    %[#{location} (#{location_type})].strip
  end

  def job_duration
    ed = end_date || Date.today
    months = (((ed.year - start_date.year) * 12 + ed.month - start_date.month) - (ed.day >= start_date.day ? 0 : 1)).round

    result = months.divmod(12)
    duration = %(#{result.first} #{'year'.pluralize(result.first)}, #{result.last} #{'month'.pluralize(result.last)})

    if currently_working_here?
      %[#{start_date.strftime('%b %Y')} - Present (#{duration})]
    else
      %[#{start_date.strftime('%b %Y')} - #{end_date.strftime('%b %Y')} (#{duration})]
    end
  end
end

app/controllers/work_experiences_controller.rb
class WorkExperiencesController < ApplicationController

  before_action :set_work_experience, only: %i[edit update destroy]

  def new
    @work_experience = current_user.work_experiences.new
  end

  def edit; end

  def create
    @work_experience = current_user.work_experiences.new(work_experience_params)
    if @work_experience.save
      render_turbo_stream(:append, 'work_experience_items', 'work_experiences/work_experience', locals: { work_experience: @work_experience })
    else
      render_turbo_stream(:replace, :bs_modal, 'shared/turbo_modal',
      locals: { form_partial: 'work_experiences/form', modal_title: 'Add new work experiences' })
    end
  end

  def update
    if @work_experience.update(work_experience_params)
      render_turbo_stream(:replace, %(work_experience_item_#{@work_experience.id}),  'work_experiences/work_experience', locals: { work_experience: @work_experience })
    else
      render_turbo_stream(:replace, :bs_modal, 'shared/turbo_modal',
      locals: { form_partial: 'work_experiences/form', modal_title: 'Edit work experiences' })
    end
  end

  def destroy
    render_turbo_stream(:remove, %(work_experience_item_#{@work_experience.id}))
  end

  private

  def set_work_experience
    @work_experience = current_user.work_experiences.find(params[:id])
  end

  def work_experience_params
    params.require(:work_experience).permit(:start_date, :end_date, :currently_working_here, :company,
                                            :employment_type, :location, :location_type, :description, :user_id, :job_title)
  end
end

app/views/work_experiences/_form.html.erb
<%= form_with model: @work_experience do |form| %>
  <div class="modal-body">
    <div class="row">
      <% if @work_experience.errors.any? %>
        <div class="error-area" style="color:red">
          <h3>
            <%= pluralize(@work_experience.errors.count, 'error') %> prohibited your work experience from being saved.
            <ul>
              <% @work_experience.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </h3>
        </div>
      <% end %>

      <div class="col-lg-12">
        <div class="form-group">
          <%= form.label :job_title, %[Job Title<span class="text-danger">*</span>].html_safe, class: "mb-2 mt-3" %>
          <%= form.text_field :job_title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :company, %q[Company<span class="text-danger">*</span>].html_safe, class: "mb-2 mt-3" %>
          <%= form.text_field :company, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= form.label :employment_type, %q[Employment Type<span class="text-danger">*</span>].html_safe, class: "mb-2 mt-3" %>
          <%= form.select :employment_type, options_for_select(WorkExperience::EMPLOYMENT_TYPE, @work_experience.employment_type), { prompt: 'Select employment type' }, { class: "form-select" } %>
        </div>

        <div class="form-group">
          <%= form.label :location, %q[Location<span class="text-danger">*</span>].html_safe, class: "mb-2 mt-3" %>
          <%= form.text_field :location, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :location_type, %q[Location Type<span class="text-danger">*</span>].html_safe, class: "mb-2 mt-3" %>
          <%= form.select :location_type, options_for_select(WorkExperience::LOCATION_TYPE, form.object.location_type), { prompt: 'Select location type' }, { class: "form-select" } %>
        </div>

        <div class="form-group row" data-controller="disable-end-date">
          <div class="col-lg-12 mt-4">
            <div class="form-check form-switch">
              <%= form.check_box :currently_working_here, class: "form-check-input", role: "switch", data: { action: "click->disable-end-date#disableEndDate", disable_end_date_target: "switch" } %>
              <%= form.label :currently_working_here, %q[I am currently working here], class: "form-check-label" %>
            </div>
          </div>

          <div class="col-log-6">
            <%= form.label :start_date, %q[Start Date<span class="text-danger">*</span>].html_safe, class: "mb-2 mt-3" %>
            <%= form.date_field :start_date, class: "form-control"%>
          </div>
          <div class="col-log-6">
            <%= form.label :end_date, "End Date", class: "mb-2 mt-3" %>
            <%= form.date_field :end_date, class: "form-control", data: { disable_end_date_target: "endDateField" } %>
          </div>
        </div>

        <div class="form-group">
        <%= form.label :description, "Description", class: "mb-2 mt-3" %>
          <%= form.text_area :description, class: "form-control", rows: 5 %>
        </div>

      </div>
    </div>
  </div>
  <div class="modal-footer">
      <%= form.submit 'Save Changes111', class: "btn btn-primary", data: { action: 'click->bs-modal#submitEnd' }%>
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/work_experiences/_work_experience.html.erb
<li class="list-group-item" id=<%= %Q[work_experience_item_#{work_experience.id}] %>>
  <div class="row">
    <div class="col-lg-9">
      <div class="d-flex justify-content-start">
        <p class="fw-bold"><%= work_experience.job_title %></p>
      </div>  
    </div>
    <div class="col-lg-3">
      <div class="d-flex justify-content-end">
        <%= link_to edit_work_experience_path(work_experience), data: { controller: 'bs-modal-form' } do %>
          <i class="bi bi-pencil-fill"></i>
        <% end %>

        <%= link_to work_experience_path(work_experience), data: { turbo_method: :delete, turbo_confirm: 'Are you sure to delete this experience? The action cannot be undo.' } do %>
          <i class="bi bi-trash text-danger"></i>
        <% end %>
      </div>
    </div>
  </div>
  <small><%= work_experience.company_with_employment_type %></small><br>
  <small><%= work_experience.job_location %></small><br>
  <small><%= work_experience.job_duration %></small><br>
</li>

app/views/work_experiences/edit.turbo_stream.erb
<%= turbo_stream.replace :bs_modal do %>
  <%= render 'shared/turbo_modal', modal_title: 'Edit work experience', form_partial: 'work_experiences/form' %>
<% end %>

app/views/work_experiences/new.turbo_stream.erb
<%= turbo_stream.replace :bs_modal do %>
  <%= render 'shared/turbo_modal', modal_title: 'Add new work experience', form_partial: 'work_experiences/form' %>
<% end %>